### ISSUE TITLE
Invalid appearance "standard", valid values are "fill" or "outline".

### ISSUE THREAD

**Issue by minahmoghadam** [hamzahamidi/ajsf#352]
* [X] MaterialDesignFrameworkModule — Material Design
* [ ] Bootstrap3FrameworkModule — Bootstrap 3
* [ ] Bootstrap4FrameworkModule — Bootstrap 4
* [ ] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  
After Upgrading Angular and Angular Material versions to v15, Angular Material has an issue with the appearance property and the add button also is hidden.

**Error: global-error-handler.ts:16 Error: MatFormField: Invalid appearance "standard", valid values are "fill" or "outline".**

- OS: [e.g. iOS] MacOs 13.2.1
- Browser [e.g. chrome, safari] Chrome
- Version [e.g. 22] 0.8.0
